# Generated by Django 4.2.2 on 2023-06-27 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(verbose_name="номер")),
                (
                    "price_per_day",
                    models.PositiveSmallIntegerField(verbose_name="цена"),
                ),
                ("beds", models.PositiveSmallIntegerField(verbose_name="кол-во мест")),
            ],
            options={
                "verbose_name": "Комната",
                "verbose_name_plural": "Комнаты",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="начало")),
                ("end_date", models.DateField(verbose_name="конец")),
                ("created_at", models.DateTimeField(verbose_name="дата резервации")),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="гость",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.room",
                        verbose_name="комната",
                    ),
                ),
            ],
        ),
    ]
